[package]

name = "pa2"
version = "0.0.1"
authors = ["Weilin Xu <mzweilin@gmail.com>", "David Evans <evans@virginia.edu>", "Brionne Godby <bgodby@brandeis.edu>", "Dimokritos Stamatakis <dimos@brandeis.edu>"]
